// <auto-generated />
using DataIngestion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataIngestion.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508150500_AddCustomerTransactionsIndex")]
    partial class AddCustomerTransactionsIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}